#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# cd packages/react-with-native
# npm version patch --no-git-tag-version --force
# git add package.json
# npm publish

# cd ../react-with-native-form
# npm version patch --no-git-tag-version --force
# git add package.json
# npm publish

# cd ../react-with-native-modal
# npm version patch --no-git-tag-version --force
# git add package.json
# npm publish

